### ISSUE TITLE
Document Methods and Classes in Wiki and redirect here as official documentation

### ISSUE THREAD

**Issue by sbshah97** [outside-edge/python-espncricinfo#14]
* As of now Documentation is very scarce for a non-developer and it'll be easier if a non-developer has to look at text rather than code. I propose we move the current README contents here and also have the Wiki structure as follows:

|-Home
|-Player
|-Summary
|-Match  

P.S: I'd love to work on this if possible!

**Comment by dwillis** [comment]
@salman-bhai my apologies for the delay in responding - I'd love to have this in the wiki and would welcome your contributions.
