### ISSUE TITLE
Match.all_innings no longer working.

### ISSUE THREAD

**Issue by olibpool** [outside-edge/python-espncricinfo#39]
Firstly, great repo has been very useful in making my small cricket website, thank you.

I have a sqlite database of all player innings in Test and ODI cricket and have been using your module to import the data, using the Match class and then .all_innings to gather all the data from the match. It was definitely working a few weeks ago but now has broken. 

It used to produce a dictionary of all the innings in a match but now only returns Nonetype regardless of the match.

**To Reproduce**
```
from espncricinfo.match import Match

m = Match(1225248)

# 1225248 is the number for the second test for Eng v Windies 2020

print(m.all_innings)
```

**Expected behavior**
It should print out all the info from each innings in the game, including info about each player's individual innings.

**Screenshots**
Here's a screenshot of the above code in action.
<img width="716" alt="Screenshot 2020-09-10 at 23 00 39" src="https://user-images.githubusercontent.com/68647683/92813675-8ee39400-f3b9-11ea-8d4c-1d72f7a7aa2c.png">

**Comment by ckola** [comment]
I have a fix for this. @dwillis Let me know i can push my changes.

**Comment by dwillis** [comment]
@olibpool @ckola this should be fixed now.

**Comment by umar1060** [comment]
Match.all_innings not working for me too!!!!please help how can i get this

**Comment by umar1060** [comment]
> I have a fix for this. [@dwillis](https://github.com/dwillis) Let me know i can push my changes.

How can i fix this @ckola @dwillis

**Comment by dwillis** [comment]
@umar1060 happy to take a look at a pull request!
