### ISSUE TITLE
[BUG] Not able to fetch player information

### ISSUE THREAD

**Issue by bhavesh0009** [outside-edge/python-espncricinfo#46]
**Describe the bug**
player.py is not able to extract player information. It is giving error - "'NoneType' object has no attribute 'find_all'"
**To Reproduce**
Just run read me sample:

from espncricinfo.player import Player
p = Player('277916')
p.name

**Expected behavior**
It should give name of player.

**Screenshots**
![image](https://user-images.githubusercontent.com/28176923/115157901-8d7ef600-a083-11eb-9aa7-f5a1cd93d460.png)
**Additional context**
AttributeError                            Traceback (most recent call last)
<ipython-input-64-37a61c4f7f70> in <module>
      1 from espncricinfo.player import Player
----> 2 p = Player('277916')
      3 p.name

C:\Python38\lib\site-packages\espncricinfo\player.py in __init__(self, player_id)
     12         self.parsed_html = self.get_html()
     13         self.json = self.get_json()
---> 14         self.player_information = self._parse_player_information()
     15         self.cricinfo_id = str(player_id)
     16         if self.parsed_html:

C:\Python38\lib\site-packages\espncricinfo\player.py in _parse_player_information(self)
     58 
     59     def _parse_player_information(self):
---> 60         return self.parsed_html.find_all('p', class_='ciPlayerinformationtxt')
     61 
     62     def _name(self):

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by aman0408** [comment]
Can I take this up?

**Comment by kakdeykaushik** [comment]
@aman0408 any updates on this ?

**Comment by WPB92** [comment]
@dwillis @aman0408 Friendly bump

**Comment by dwillis** [comment]
I've pushed a fix for this - it removes some of the methods that depend on HTML parsing for now but the `Player` object remains mostly intact.
