### ISSUE TITLE
[BUG] Maximum Excursion Error

### ISSUE THREAD

**Issue by GG628** [outside-edge/python-espncricinfo#47]
**Describe the bug**
Excursion Error when calling methods within the module

**To Reproduce**
Run Sample code in the overview page of the module

**Expected behavior**
No MaximumExcursion Error

**Screenshots**
N/A

**Additional context**
https://stackoverflow.com/questions/67165137/espn-cricinfo-maximum-recursion-depth-exceeded/67166173?noredirect=1#comment118744395_67166173

Please see the following question I asked on StackOverflow with the exact problem I encountered. 

Thanks a lot to anyone that can help

**Comment by dwillis** [comment]
This should be fixed now.
